### ISSUE TITLE
ui-sref not replaced on render

### ISSUE THREAD

**Issue by glennpierce** [amarsahinovic/django-zurb-foundation#8]
Hello

The built in test index page "Welcome to Foundation" appears to work fine. I then decided to try to render http://foundation.zurb.com/apps/app-templates/travel/#!/

I did this by copying the css and index.html in the correct django blocks.

The page displays OK but the navbar links don't work at all. I am guessing the ui-sref elements should be replaced at some point and are not.

The template I created can be seen at http://pastie.org/10510658

I'm sure I am doing something silly having just started. I see no browser error and $(document).foundation(); is called.

Grateful for any advice.
Thanks

**Comment by amarsahinovic** [comment]
Hi,
Sorry for not responding sooner.

This package only includes foundation for sites (http://foundation.zurb.com/sites.html) and not for apps (http://foundation.zurb.com/apps.html). By quick googling, ui-sref appears to be something related to angulars ui-router (https://github.com/angular-ui/ui-router/wiki/Quick-Reference#ui-sref), which I unfortunately do not use, so I can't help you there.

You should probably follow official install guide for foundation for apps to get started.

**Comment by glennpierce** [comment]
Thanks . The problem was / is i'm not familiar with foundation so was not aware of the differences.
I may see if I can make do with sites. 
So confusing having two frameworks with similar names. Not sure what they were thinking.

Thanks for the feedback.
